use car_rental;
INSERT INTO admin (email,password) VALUES ('admin@gmail.com',md5('111'));
INSERT INTO office(office_id,location)VALUES('1','Alexandria');
INSERT INTO office(office_id,location)VALUES('2','Cairo');
INSERT INTO car (car_plate,model,model_year,color,daily_price,office_id,status,image) VALUES ('AB111','Cherry',2015,'Black',1000,1,'rented','cherry.jpg');
INSERT INTO car (car_plate,model,model_year,color,daily_price,office_id,status,image) VALUES ('CD110','Toyota',2018,'White',1500,2,'available','toyota.jpeg');
INSERT INTO car (car_plate,model,model_year,color,daily_price,office_id,status,image) VALUES ('ER110','BMW',2019,'Blue',1500,2,'available','bmw.jpg');
INSERT INTO car (car_plate,model,model_year,color,daily_price,office_id,status,image) VALUES ('PS110','KIA',2020,'Black',1500,1,'available','kia.jpg');
INSERT INTO car (car_plate,model,model_year,color,daily_price,office_id,status,image) VALUES ('FT110','Mercedes',2022,'White',1500,2,'available','mercedes.jpg');
INSERT INTO car_status(car_plate,status,start_date,end_date) VALUES ('AB111','available','2022-12-23','2022-12-24');
INSERT INTO car_status(car_plate,status,start_date) VALUES ('CD110','available','2022-12-23');
INSERT INTO car_status(car_plate,status,start_date) VALUES ('ER110','available','2022-12-23');
INSERT INTO car_status(car_plate,status,start_date) VALUES ('PS110','available','2022-12-23');
INSERT INTO car_status(car_plate,status,start_date) VALUES ('FT110','available','2022-12-23');
INSERT INTO customer(cust_id,name,email,password) VALUES ('1','Asala','asala@gmail.com',md5('111')) ;
INSERT INTO customer(cust_id,name,email,password) VALUES ('2','Zahraa','zahraa@gmail.com',md5('111')) ;
INSERT INTO customer(cust_id,name,email,password) VALUES ('3','Farah','farah@gmail.com',md5('111')) ;
INSERT INTO registration(register_no,car_plate,cust_id,office_id,payment,pay_date,penalty,start_date,end_date,return_date)
VALUES(1,'AB111',2,1,3000,'2022-12-25',0,'2022-12-25','2022-12-28','2022-12-28');
INSERT INTO car_status(car_plate,status,start_date,end_date) VALUES ('AB111','rented','2022-12-25','2022-12-28');
INSERT INTO car_status(car_plate,status,start_date) VALUES ('AB111','available','2022-12-29');
INSERT INTO car (car_plate,model,model_year,color,daily_price,office_id,status,image) VALUES ('PS110','KIA',2020,'Black',1500,1,'available','kia.jpg');
INSERT INTO car_status(car_plate,status,start_date) VALUES ('PS110','available','2022-12-23');